### PR TITLE
Add various improvements

### PR DESCRIPTION
**Pull request by rgreinho**
* Make the role testable with molecule
* Make the role idempotent
* Fix the trailing new lines and white spaces
* Do not delete the Hubot directory on each run
* Remove unnecessary defaults
* Add handler to enable the Hubot service
* Execute the tasks with the appropriate user
* Better management of the package installation
* Refactor the tasks to eliminate duplicates
* Add Test Infra test

### CODE REVIEW

**Comment by brianshumate** [comment]
Wow, thanks for the great PR!

I'll have a look and try to get this merged soon.

**Comment by brianshumate** [comment]
Hey Rémy,

Everything looks great so far, but I did not find a `requirements.txt` for the Molecule deps. I suppose I can freeze what I have from my virtualenv and include that in a commit though. I will just include it in the root of the project unless it makes sense to put it elsewhere.

This is really awesome stuff and again, I appreciate your contribution.

**Comment by rgreinho** [comment]
I'm glad you like the PR :)

Regarding ``Molecule``, it is not a dependency for the role itself, that's why there is no ``requirements.txt`` file. ``Molecule`` is an external tool we use to test our roles (https://molecule.readthedocs.org/en/master/), to ensure they run properly on various platforms, check idempotence, run some Test Infra tests, etc. I'm not sure it makes sense to add it to the role, as it will be for developers only.

**Comment by brianshumate** [comment]
Ahh understood, I was just wondering since the README is updated and [references using one](https://github.com/brianshumate/ansible-hubot/pull/12/files#diff-04c6e90faac2675aa89e2176d2eec7d8R186). Could the step there just be to `pip install ansible molecule` instead then?

**Comment by rgreinho** [comment]
My bad, and good catch! That was a mistake in the steps. I update the PR accordingly.

**Comment by brianshumate** [comment]
No worries, I'll merge it now.

Cheers and Happy Holidays!

**Comment by rgreinho** [comment]
Awesome! Thank you and Happy Holidays too :)

**Pull request merged**
